#version: '3.4'

services:
  razorpagesapp:
    image: razorpagesapp
    container_name: razorpagesapp
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
    ports:
      - "5000:5000"
#      - "5001:5001"
    depends_on:
      - razorpagesapp.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Moscow
      - ConnectionStrings__Database=Host=razorpagesapp.database;Port=5432;Database=SmartSpaceDb;Username=YourLogin;Password=YourPassword;Include Error Detail=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

  razorpagesapp.database:
    image: postgres:17
    container_name: razorpagesapp.database
    environment:
      - POSTGRES_DB=SmartSpaceDb #usersdbSSP
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=combust0201
    volumes:
      - ./.containers/razorpagesapp-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
